"""Inverse problem: recover hidden spring parameters from an observed shape.

This is the payoff of a *differentiable* simulator and a canonical SciML task —
system identification. We hide a non-uniform set of rest lengths inside the
chain, observe only the shape it settles into, then gradient-descend the rest
lengths (from a uniform guess) through the entire rollout with
``jax.value_and_grad`` until the simulated shape matches the observation.

Because the target is generated by the simulator itself, it is exactly
reachable, and the loss drops to numerical zero.

Run::

    uv run --extra viz python examples/inverse_design.py
"""

from __future__ import annotations

import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np
from _common import output_path

from jax_spring_sim import fit_rest_lengths, make_chain, simulate_final

N = 20
N_STEPS = 250
DT = 1e-2
OPT_STEPS = 400


def main() -> None:
    state, system = make_chain(N, stiffness=200.0, damping=0.99)

    # Ground-truth (hidden) rest lengths: a smooth non-uniform pattern.
    edge_x = jnp.linspace(0.0, 1.0, N - 1)
    true_rest = system.rest_length * (1.0 + 0.4 * jnp.sin(2.0 * jnp.pi * edge_x))
    target = simulate_final(state, system._replace(rest_length=true_rest), DT, N_STEPS).pos

    # Forward pass with the uniform initial guess, then fit.
    before = simulate_final(state, system, DT, N_STEPS).pos
    rest_length, losses = fit_rest_lengths(
        state, system, target, DT, N_STEPS, opt_steps=OPT_STEPS, lr=0.05
    )
    after = simulate_final(state, system._replace(rest_length=rest_length), DT, N_STEPS).pos

    before, after, target_np = map(np.asarray, (before, after, target))
    losses = np.asarray(losses)
    rest_err = float(jnp.linalg.norm(rest_length - true_rest))
    print(f"shape loss: {losses[0]:.4f} -> {losses[-1]:.2e}  ({losses[0] / losses[-1]:.0f}x)")
    print(f"||recovered L0 - true L0||: {rest_err:.4f}")

    fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(12, 5))
    ax0.plot(target_np[:, 0], target_np[:, 1], "k--o", ms=5, label="observed (target)")
    ax0.plot(before[:, 0], before[:, 1], "-o", ms=4, alpha=0.6, label="initial guess (uniform L₀)")
    ax0.plot(after[:, 0], after[:, 1], "-o", ms=4, label="recovered L₀")
    ax0.set_aspect("equal")
    ax0.set_title("System identification: settled shape")
    ax0.set_xlabel("x")
    ax0.set_ylabel("y")
    ax0.legend()

    ax1.semilogy(losses)
    ax1.set_title("Loss via Adam, differentiated through the rollout")
    ax1.set_xlabel("optimisation step")
    ax1.set_ylabel("mean squared distance")
    ax1.grid(True, which="both", alpha=0.3)

    fig.tight_layout()
    path = output_path("inverse_design.png")
    fig.savefig(path, dpi=130)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
